-- MySQL Script generated by MySQL Workbench
-- 05/07/16 13:43:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_seguridad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_seguridad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_seguridad` DEFAULT CHARACTER SET utf8 ;
USE `bd_seguridad` ;

-- -----------------------------------------------------
-- Table `bd_seguridad`.`enlace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_seguridad`.`enlace` (
  `idenlace` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `ruta` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idenlace`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_seguridad`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_seguridad`.`rol` (
  `idrol` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_seguridad`.`rol_enlace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_seguridad`.`rol_enlace` (
  `idrol` INT(11) NOT NULL,
  `idenlace` INT(11) NOT NULL,
  PRIMARY KEY (`idrol`, `idenlace`),
  INDEX `fk_rol_has_enlace_enlace1_idx` (`idenlace` ASC),
  INDEX `fk_rol_has_enlace_rol1_idx` (`idrol` ASC),
  CONSTRAINT `fk_rol_has_enlace_rol1`
    FOREIGN KEY (`idrol`)
    REFERENCES `bd_seguridad`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_has_enlace_enlace1`
    FOREIGN KEY (`idenlace`)
    REFERENCES `bd_seguridad`.`enlace` (`idenlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_seguridad`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_seguridad`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_seguridad`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_seguridad`.`usuario_rol` (
  `idusuario` INT(11) NOT NULL,
  `idrol` INT(11) NOT NULL,
  PRIMARY KEY (`idusuario`, `idrol`),
  INDEX `fk_usuario_has_rol_rol1_idx` (`idrol` ASC),
  INDEX `fk_usuario_has_rol_usuario_idx` (`idusuario` ASC),
  CONSTRAINT `fk_usuario_has_rol_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bd_seguridad`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_rol_rol1`
    FOREIGN KEY (`idrol`)
    REFERENCES `bd_seguridad`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_seguridad`.`socio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_seguridad`.`socio` (
  `idsocio` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idsocio`),
  INDEX `fk_socio_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_socio_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bd_seguridad`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_seguridad`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_seguridad`.`trabajador` (
  `idtrabajador` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idtrabajador`),
  INDEX `fk_trabajador_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_trabajador_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bd_seguridad`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
